kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: chaos-manager

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: role-chaos-manager
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*" ]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-default-manager-dgazd
  namespace: default
subjects:
- kind: ServiceAccount
  name: chaos-manager
  namespace: default
roleRef:
  kind: Role
  name: role-chaos-manager
  apiGroup: rbac.authorization.k8s.io
